// GENERATED by setup.dart from Fearless743/mihomo_core API — do not edit by hand
// ignore_for_file: constant_identifier_names

/// Latest mihomo version from Fearless743/mihomo_core releases.
const String kCoreVersionFromSource = 'v1.19.23';
